language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install . codecov mock pytest pytest-cov pylint
script:
- py.test
- pylint influxalchemy --disable useless-object-inheritance,bad-mcs-classmethod-argument
after_success:
- codecov
deploy:
  provider: pypi
  user: amancevice
  password:
    secure: >
      KcT5EOQSnhmfs49RSA7Lfa+2O4IsZcuYyMQBVUDxz2eQIXHKP6WWTmAjVwFYhnlnBUoTRINie
      AhCElQraTdm55AAy9z4GwN+aXBLvnvnVZseLwCz6p25snYR9W47RykaLmvgbBvy20pvKBAWGv
      T/9KfD2L4tL5vQrVluuLbwBwCqK89KAPBc9wmaAeIQfAWb7ZlOAb3ts+k9FfUfpqjxUo5b1wW
      POAvCcfmu/5qYNcEuowzqImQPzAX5sRZgXnp2/W9SRSMjt/DpxfG2DdGgYo0Vpm2WfZ4lvi9R
      zqD4mU6PtaO/R0DexquN1HxcfEUmVxvgpVqCPMlwf//H0GEXk8FfxK8b/bKIiBCzW3CP6chce
      K+3gvggCZKpQWHa8/1oeq0kk8UpVMWFutCaj7/T3rPE6F9earrPkMkPnX/pXRljz5E90mBryb
      lYPW6cj4u32OeH1GpOjUU1eJHMsgtQ9L0XsqC5kQ4wzspxjdUR4TLdilxD1YLNIQkHnnXtb1d
      5CdMTLPiTPoM1LYpnF/IDYGFqzDdC4SNpdocMjWW0rWsJ5p+4FGswBOi9HKpLbBC8Vy8NIyV5
      fUji+N3+CJ38B8budcltXql6yjld4v6yLDEMu7fVwEsjI+vDo0+VAkX9jEU7oYxgCgkwySjUX
      PWwdcwXikqX/PAI/rjWVlMbb/I=
  on:
    distributions: sdist bdist_wheel
    python: '3.6'
    repo: amancevice/influxalchemy
    tags: true
